### ISSUE TITLE
Clustered factories should be broken out when zoom level is high

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/frontend#144] opened 2022-03-30 12:46 UTC
**Describe the bug**
請清晰詳細的描述這個問題

**To Reproduce**
列出可以重現問題的步驟：

**Expected behavior**

**Screenshots**
截圖

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdon** [comment] 2022-04-09 05:37
duplicate of #150 ?

**Comment by Yukaii** [comment] 2022-04-09 05:53
> duplicate of #150 ?

you're right

**Closed** 2022-04-09 05:54 UTC
Labels: bug
